#! /usr/bin/env python3

import argparse
import shutil
import subprocess
import os

dirname = os.path.dirname(os.path.realpath(__file__))

parser = argparse.ArgumentParser(description='Install dependencies for ' +
                                 'TwinePM\'s web server container.')

args = parser.parse_args()

base_dir = '/etc/twine-package-manager/'
with open('/usr/share/nginx/html/index.php', 'w') as f:
    f.write('<?php require_once "{}logic/index.php"; ?>'.format(base_dir))

shutil.copy2('{}web/site.conf'.format(cwd), '/etc/nginx/conf.d/default.conf')
shutil.copy2('{}web/mime.types'.format(cwd), '/etc/nginx/')

print('Completed installing web dependencies.')